### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by rnpgeo** [lmotta/catalogpl_plugin#1]
The plugin seems to have stopped working, as it is returning "No found images" for all searches.
I have tested it on Mac 10.11.6 and Windows 10 with QGIS 2.18.2, with a working api key.

**Comment by lmotta** [comment]
The plugin was update to Planet  Version API 1.
Please try again

**Comment by giswqs** [comment]
I was able to search images and download thumbnails. However, when I tried to download images for selected features, I got the following error. And the plugin became grey out, which is no longer clickable. 


2017-12-20T11:34:42	1	Traceback (most recent call last):
			  File "/home/user/.qgis2/python/plugins/catalogpl_plugin/catalogpl.py", line 1013, in downloadImages
			    dataLocal = { 'totalError': 0, 'step': 0, 'ltgRoot': ltgRoot }
			NameError: global name 'ltgRoot' is not defined

**Comment by lmotta** [comment]
Fixed in version 1.7.1.
Thanks Dr. Qiusheng Wu

**Comment by giswqs** [comment]
It works now! Thank you for your speedy fix! And thank you very much for developing such an amazing tool! It makes my life much easier.
